### ISSUE TITLE
Stretched face on Android Chrome

### ISSUE THREAD

**Issue by marcusx2** [jeeliz/jeelizFaceFilter#292]
If you try out [this example](https://jeeliz.com/demos/faceFilter/demos/threejs/gltf_fullScreen/) on your Android Chrome, your face will be stretched vertically.

I already created a bug report on the [threejs github](https://github.com/mrdoob/three.js/issues/25298), but one of the repo managers asked that the issue should be handled here instead...

**Comment by marcusx2** [comment]
Unfortunately, no. In the _JeelizResizer.js_, in the _apply_sizeCanvas_ function, the css width and height inside _if (_isApplyCSS){_ overwrites what you have in the _styleFullScreen.css_ though. I tried removing that _if_ but it didn't solve the issue either.

On another note, the issue doesn't happen on iOS Safari. It seems to be a problem only on Android.

**Comment by marcusx2** [comment]
> I don’t have an android phone to test and indeed there is no issue with iOS. Can you try tinkering with the css to see if it solves the issue ? You can also mail me a device with the issue.

I'm using a Samsung S8. I tried tinkering with the CSS to no avail. However here's some information that might help. The following CSS makes an [HTLMVideo element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) fullscreen while keeping the aspect ratio (the transform scale is just to flip horizontally). It works on Android and iPhone.

`_videoElement.setAttribute('style', 'width: 100vw;height: 100vh;object-fit: cover;position: absolute;top: 0;left: 0; transform: scale(-1, 1);');`

I tried using the css above on the `styleFullScreen.css` but it didn't work though.

**Comment by marcusx2** [comment]
@xavierjs I found out what the issue is and how to fix it, but not the proper solution. The problem is the apply_sizeCanvas function and the __overSamplingFactor_, which results to 4. If I hardcode 2 instead(3 also doesn't work), the webcam feed shows up properly

```
function apply_sizeCanvas(width, height){
    _whCanvasPx = [
      Math.round(2 * width),
      Math.round(2 * height)
    ];

	console.log(_overSamplingFactor);
    // set canvas resolution:
    _domCanvas.setAttribute('width',  _whCanvasPx[0]);
    _domCanvas.setAttribute('height', _whCanvasPx[1]);
	
	console.log('_whCanvasPx[0]: ' + _whCanvasPx[0] + ' _whCanvasPx[1]: ' + _whCanvasPx[1]);
	console.log('width: ' + width + ' height: ' + height);

    // canvas display size:
    if (_isApplyCSS){
      _domCanvas.style.width = width.toString() + 'px';
      _domCanvas.style.height = height.toString() + 'px';
    }
  }
```

So, it seems that different devices support different oversampling factors, or maybe it's just android. If you detect that it's Android and set the oversampling factor to 2, it will solve the issue. Ideally the code should be able to figure out what is the max sampling factor the device supports though.

**Comment by xavierjs** [comment]
Hi,

Thank you for these precisions.
I think that the issue is that:

- at the initialization, `JeelizResizer` will set the canvas resolution as `window.innerWidth * window.innerHeight`. There is the URL bar
- then the URL bar is hidden by the browser. `window.innerHeight` should increase. But for some reason no `window.resize` event is triggered. The canvas resolution stays the same (wrong value for the height). But the canvas is stretched in fullscreen

**Comment by xavierjs** [comment]
I have pushed a potential fix. It forces canvas resizing 500 milliseconds after init in JeelizResizer here: https://github.com/jeeliz/jeelizFaceFilter/blob/b133c798851e99bc1ef13c4b2f58652c7832d902/helpers/JeelizResizer.js#L262 
Can you try it? And if it does not work increase the `500` timeout to `2000` for example and wait 2 seconds?

Thanx a lot!

**Comment by marcusx2** [comment]
Unfortunately, it did not work. I tried with 2 seconds as well. I also made a few more discoveries. It seems that even if I set the oversampling factor to 2, I still get a small distortion on Android Chrome. However, the issue **does not** happen on Firefox for Android. Don't know about other browsers, but it seems that this problem is browser specific. It just looks like on some browsers the canvas attribute width/height needs to be the same as the css width/height, otherwise it distorts. Maybe there's a fix to this, but it looks like it's one of those CSS issues where it works on one browser, but doesn't on the other, and you need to find a common CSS that works across all browsers, which can be very difficult.

**Comment by xavierjs** [comment]
Hi
This is really weird. Can you try with the latest commit? I blocked the page display scale using a specific META tag.
Currently the canvas attribute width and height (i.e. the resolution) is strictly proportional to canvas CSS attribute (the proportionality factor is the devicePixelRatio), so I don't understand what can go wrong.

**Comment by marcusx2** [comment]
The meta tag code finally fixed the issue, without the need of this `window.setTimeout(on_windowResize, 500); `

> Currently the canvas attribute width and height (i.e. the resolution) is strictly proportional to canvas CSS attribute (the proportionality factor is the devicePixelRatio), so I don't understand what can go wrong.

Yes, this is true. I don't understand why it stretches either, but the meta tag solved the issue. Make sure to also test on all the iPhone browsers as well!

**Comment by xavierjs** [comment]
It does not change the `apply_sizeCanvas` issue. Maybe there were some zoom in or out with different values on X and Y axis. It is really weird... Thank you for your help, I have added the fix to another demo.

**Comment by Platform-Group** [comment]
> > I don’t have an android phone to test and indeed there is no issue with iOS. Can you try tinkering with the css to see if it solves the issue ? You can also mail me a device with the issue.
> 
> I'm using a Samsung S8. I tried tinkering with the CSS to no avail. However here's some information that might help. The following CSS makes an [HTLMVideo element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) fullscreen while keeping the aspect ratio (the transform scale is just to flip horizontally). It works on Android and iPhone.
> 
> `_videoElement.setAttribute('style', 'width: 100vw;height: 100vh;object-fit: cover;position: absolute;top: 0;left: 0; transform: scale(-1, 1);');`
> 
> I tried using the css above on the `styleFullScreen.css` but it didn't work though. It's like the canvas ignores the style or it doesn't work for some other reason. Maybe some other math that screws up the style or something...

Weirdly enough that styling causes all entities to vanish for me, no errors in the console. It does fix the camera stretch though
