### ISSUE TITLE
Use GLTF/GLB instead of  JSON object scene in format 4 in demos/threejs/glassesVTO/JeelizThreeGlassesCreator

### ISSUE THREAD

**Issue by resun-c** [jeeliz/jeelizFaceFilter#310]
I was wondering if it is possible to use GLTF/GLB with [JeelizThreeGlassesCreator](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/JeelizThreeGlassesCreator.js) instead of using JSON object scene in format 4 as they don't have much support accorse tools like Blender.

Thanks!

**Comment by hharshas** [comment]
I may find this interesting and wanna try out to do changes cause glb and gltf are easier  to load with threejs using the GLTFLoader and hooks like useLoader, making the process seamless.

**Comment by xavierjs** [comment]
Hi

Yes it is possible, you are welcome to submit a PR for this.

**Comment by xavierjs** [comment]
Hi @resun-c @hharshas 
Sure, it would be a good idea. You are welcome to submit a PR for this.

**Comment by resun-c** [comment]
I don't have much experience with Three.js. So, I would request your assistance.

Thanks!

**Comment by xavierjs** [comment]
You can find all the documents, tutorials, and examples online, especially at https://webglacademy.com (I created this interactive tutorial platform for my teaching of 3D programming ).

**Comment by resun-c** [comment]
It shows "Page Not Found bro".

**Comment by xavierjs** [comment]
Oops sorry I fixed the link in my previous post (I put HTTPS:// instead of HTTP:// )

**Comment by resun-c** [comment]
the link is still incorrect; you have only changed the text.

**Comment by resun-c** [comment]
Can somebody help me with these files:

1. [/demos/threejs/glassesVTO/models3D/face.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/face.json)
2. [/demos/threejs/glassesVTO/models3D/glassesFrames.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/glassesFrames.json)
3. [/demos/threejs/glassesVTO/models3D/glassesFramesBranchesBent.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/glassesFramesBranchesBent.json)
4. [/demos/threejs/glassesVTO/models3D/glassesLenses.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/glassesLenses.json)

What are they (I am expecting a through explanation)? Specifically, the [/demos/threejs/glassesVTO/models3D/face.json](https://github.com/jeeliz/jeelizFaceFilter/blob/master/demos/threejs/glassesVTO/models3D/face.json) file. What purpose does it serve?

**Comment by resun-c** [comment]
I tried to tweak it a bit and I was able to use a gltf file as the source of the glass. But there's an issue! The glass doesn't properly fit on the face and the glass is moving on the opposite direction when the head move around.

Here's a demo version: https://arfilter-7a618.web.app

All the demo under /demo has multiple JSON files for lense, branch and frame and they are using the JSON data to feed THREE.BufferGeometryLoader() and creating a mesh along with some textures. Then those meshes are put into a Object3D which is then added to the face. Seemingly, those meshes perfectly fit the face. However, the glass I am using is a single mesh. Is it the main issue?

Thanks!

**Comment by xavierjs** [comment]
Hello @resun-c 

Please submit a PR with your code in the newly created `/demos/threejs/glassesVTOJSON/` folder, I will take a look.

Best,
Xavier
